version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fan-athletics_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fan-athletics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  smtp:
    image: rnwood/smtp4dev
    container_name: fan-athletics_smtp
    ports:
      - "8082:80"
      - "25:25"

volumes:
  pgdata: